import type { Metadata } from "next";
import localFont from "next/font/local";
import {Hind_Vadodara} from "next/font/google";
import MainLayoutContainer from "@/layouts/mainLayoutContainer";
import "./globals.scss";
import UserContextProvider from "@/contexts/userContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const hindVandodara = Hind_Vadodara({
  variable: "--font-hind-vadodara",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})



export const metadata: Metadata = {
  title: "onStage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hindVandodara.variable} ${geistSans.variable} ${geistMono.variable}`}>
        <UserContextProvider>
          <MainLayoutContainer>
            {children}
          </MainLayoutContainer>
        </UserContextProvider>
      </body>
    </html>
  );
}
